// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ9FEFHhq_4jx8X-Tdv-6UpytZ3bVN5mo',
    appId: '1:741373453753:web:ee02d67602399f04de0268',
    messagingSenderId: '741373453753',
    projectId: 'authtutorial-a8144',
    authDomain: 'authtutorial-a8144.firebaseapp.com',
    storageBucket: 'authtutorial-a8144.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37qIuVlZNi37rOhENIGajPg2n_qCYEow',
    appId: '1:741373453753:android:a28a454de480b7e0de0268',
    messagingSenderId: '741373453753',
    projectId: 'authtutorial-a8144',
    storageBucket: 'authtutorial-a8144.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSja1PpPW3Dy9lo-ds2PM_nXqzWQKMWmo',
    appId: '1:741373453753:ios:794a632ae4d89fb3de0268',
    messagingSenderId: '741373453753',
    projectId: 'authtutorial-a8144',
    storageBucket: 'authtutorial-a8144.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSja1PpPW3Dy9lo-ds2PM_nXqzWQKMWmo',
    appId: '1:741373453753:ios:794a632ae4d89fb3de0268',
    messagingSenderId: '741373453753',
    projectId: 'authtutorial-a8144',
    storageBucket: 'authtutorial-a8144.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ9FEFHhq_4jx8X-Tdv-6UpytZ3bVN5mo',
    appId: '1:741373453753:web:36eba1b1b1e733efde0268',
    messagingSenderId: '741373453753',
    projectId: 'authtutorial-a8144',
    authDomain: 'authtutorial-a8144.firebaseapp.com',
    storageBucket: 'authtutorial-a8144.appspot.com',
  );
}
